name: arna_animations
description: A package that provides basic animations to your flutter application.
version: 1.0.0
homepage: https://github.com/MahanRahmati/arna_animations

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
